spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # 启用 publisher confirms & returns （可靠性）
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true